name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        name: Create token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.SAWMILLS_REPO_APP_ID }}
          private_key: ${{ secrets.SAWMILLS_APP_PRIVATE_KEY }}

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.create_token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
